config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :restaurants do
    resources :reviews
  end

  root to: "restaurants#index"

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reviews, dependent: :destroy

	# has_many :reviews do
	#   def build_with_user(attributes = {}, user)
	#     attributes[:user] ||= user
	#     build(attributes)
	#   end
	# end

	def build_review(review_params, user)
    self.reviews.new(thoughts: review_params["thoughts"], rating: review_params["rating"], user: user)
  end

	validates :name, length: {minimum: 3}, uniqueness: true

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :user

	validates :rating, inclusion: (1..5)
	validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :reviews
	has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def has_reviewed?(restaurant)
  	reviewed_restaurants.include? restaurant
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	
	before_action :authenticate_user!, :except => [:index, :show]

	def index
		"Hello from the index action"
	end

	def show
		@restaurant = Restaurant.find(params[:id])
	end 

	def new
		@restaurant = Restaurant.new
	end

	def create
	  @restaurant = Restaurant.new(restaurant_params)
	  if @restaurant.save
	    redirect_to restaurants_path
	  else
	    render 'new'
	  end
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def update
		@restaurant = Restaurant.find(params[:id])
		@restaurant.update(restaurant_params)

		redirect_to "/restaurants"
	end

	def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end

	#utility method
	def restaurant_params
    params.require(:restaurant).permit(:name)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def new
		@restaurant = Restaurant.find(params[:restaurant_id])
  	@review = Review.new
	end

	def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.build_review review_params, current_user

    if @review.save
      redirect_to restaurants_path
      flash[:notice] = "Review successfully created"
    else
      # Use locales instead for custom error message
      if @review.errors[:user]
        redirect_to restaurants_path, alert: 'You have already reviewed this restaurant'
      else
        render :new
      end
    end
  end

  #utility method
	def review_params
	  params.require(:review).permit(:thoughts, :rating)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yelp2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/restaurants/edit.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<% if Restaurant.all.any? %>
  <% Restaurant.all.each do |restaurant| %>
    <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
    <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>
    <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>
    <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>
    <h3>Reviews for <%= restaurant.name %></h3>

<% if restaurant.reviews.any? %>
  <ul>
    <% restaurant.reviews.each do |review| %>
      <li>
        <%= review.thoughts %>, <strong><%= review.rating %></strong>/5
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No reviews.</p>
<% end %>
  <% end %>
<% else %>
  <h1>No restaurants yet</h1>
<% end %>

<%= link_to 'Add a restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <section id="errors" >
    <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<p><%= @restaurant.name %></p>
<p><%= @restaurant.description %></p>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %>
  <%= f.submit 'Leave Review' %>
<% end %>